#!/bin/sh

# Root directory
BASE_DIR=~/Dev
LOG=/var/log/archive_dev.log
OLD=200

# Function to archive entire directory
archive_directory() {
    DEL_DIR="$1"
    tar -cf "$DEL_DIR.tar" -C "$DEL_DIR" . >> "$LOG"
    rm -rf "$DEL_DIR" >> "$LOG"
}

# Get list of directories in root_directory
for dir in "$BASE_DIR"/*/; do
    if [ -d "$dir" ]; then
        # Get the modification time of the directory
        MOD_TIME=$(stat -c %Y "$dir")
        # Get current time in seconds since epoch
        CURRENT_TIME=$(date +%s)
        # Calculate difference in days
        DAYS_DIFF=$(( (CURRENT_TIME - MOD_TIME) / (60*60*24) ))

        # Check if directory is older than 200 days (approximately 7 months)
        if [ "$DAYS_DIFF" -gt $OLD ]; then
            # echo "$dir"
            # Call function to archive entire directory
            archive_directory "$dir"
        fi
    fi
done

exit 0
